name: composite
on:
  push:
    branches:
       -master

env:
  deploy_powershell_script:  "D:\\github-deploy-ps.ps1"


jobs:
  build:
    runs-on: windows-latest

    env:
      stop_powershell_script:  "D:\\stop-website-ps.ps1"
      upload_artifacts_path: "./pashdotnetcorewebapp"
      
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/ChengSueYun/MES.Order
      with: 
        name: OctoCat
        upload-artifacts-path: "$upload_artifacts_path"
    - run: echo "$deploy_powershell_script"
      shell: pwsh
    - run: echo "$upload_artifacts_path"
      shell: pwsh
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
