name: Hugo Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
 
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.57.2'
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.COMMIT_SECRET }}
          external_repository: chengsueyun.github.io/MES.Order/ # <- 改成你自己的 user github page
          publish_branch: master # <- 遠端 repo 的目標分支
          publish_dir: ./public # <- 指定編譯後的成品放置的資料夾
